### ISSUE TITLE
 Serial: Serial read error

### ISSUE THREAD

**Issue by jbarneson** [TD22057/insteon-mqtt#132]
After upgrading to 0.6.7, my logs are filled with these serial read errors. Maybe this is coincidental to the upgrade and there is a hardware problem. Can anyone shed light on what this error means? 

I'm running on a raspberry pi with a USB plm (the wireless, not wired version). 

`2019-03-14 06:49:14 ERROR Serial: Serial read error from /dev/ttyUSB0
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/insteon_mqtt/Protocol.py", line 309, in _data_read
    msg = msg_class.from_bytes(self._buf)
  File "/usr/lib/python3.6/site-packages/insteon_mqtt/message/InpAllLinkFailure.py", line 38, in from_bytes
    assert raw[2] == 0x01
AssertionError
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/insteon_mqtt/network/Serial.py", line 184, in read_from_link
    self.signal_read.emit(self, data)
  File "/usr/lib/python3.6/site-packages/insteon_mqtt/Signal.py", line 47, in emit
    slot(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/insteon_mqtt/Protocol.py", line 311, in _data_read
    LOG.exception()
TypeError: exception() missing 1 required positional argument: 'msg'`

**Comment by TD22057** [comment]
Thanks.  Sometimes weird sequences show up by I wouldn't expect to see very many of them.  The 2nd part of that message is an error in a logging statement in the code.  I've fixed that in the dev branch.
