### ISSUE TITLE
cannot import name 'db'

### ISSUE THREAD

**Issue by house97** [TD22057/insteon-mqtt#16]
I'm sure it's me, but I really thought I had done everything right in installing and configuring this project, using the instructions provided in auto_start.md.  However, when attempting to run "insteon-mqtt start config.yaml" I am seeing:
insteon-mqtt start config.yaml
Traceback (most recent call last):
  File "/opt/insteon-mqtt/bin/insteon-mqtt", line 3, in <module>
    import insteon_mqtt
  File "/opt/insteon-mqtt/lib/python3.4/site-packages/insteon_mqtt/__init__.py", line 17, in <module>
    from . import cmd_line
  File "/opt/insteon-mqtt/lib/python3.4/site-packages/insteon_mqtt/cmd_line/__init__.py", line 16, in <module>
    from .main import main
  File "/opt/insteon-mqtt/lib/python3.4/site-packages/insteon_mqtt/cmd_line/main.py", line 11, in <module>
    from . import start
  File "/opt/insteon-mqtt/lib/python3.4/site-packages/insteon_mqtt/cmd_line/start.py", line 6, in <module>
    from .. import config
  File "/opt/insteon-mqtt/lib/python3.4/site-packages/insteon_mqtt/config.py", line 13, in <module>
    from . import device
  File "/opt/insteon-mqtt/lib/python3.4/site-packages/insteon_mqtt/device/__init__.py", line 29, in <module>
    from .Base import Base
  File "/opt/insteon-mqtt/lib/python3.4/site-packages/insteon_mqtt/device/Base.py", line 10, in <module>
    from .. import db
  File "/opt/insteon-mqtt/lib/python3.4/site-packages/insteon_mqtt/db/__init__.py", line 15, in <module>
    from .Device import Device
  File "/opt/insteon-mqtt/lib/python3.4/site-packages/insteon_mqtt/db/Device.py", line 11, in <module>
    from .. import handler
  File "/opt/insteon-mqtt/lib/python3.4/site-packages/insteon_mqtt/handler/__init__.py", line 38, in <module>
    from .DeviceDbGet import DeviceDbGet
  File "/opt/insteon-mqtt/lib/python3.4/site-packages/insteon_mqtt/handler/DeviceDbGet.py", line 7, in <module>
    from .. import db
ImportError: cannot import name 'db'

What in the world have I messed up here?

**Comment by TD22057** [comment]
Hmmm - not sure.  That's a circular package import (I'm assuming init.py is really __init__.py - not sure what that's not in the file path) but it works fine for me.  The only thing I can think of is that I'm using python 3.5 and you're on python 3.4.  Let me see if I can figure out an easy way to get an older version of python on my system and I'll try it out.

**Comment by TD22057** [comment]
I think is is python 3.4.  I found [this reference](https://docs.python.org/3/whatsnew/3.5.html#other-language-changes) in the release notes for 3.5 which sounds like what we're seeing.  I should be able to remove the circular import so it will work on python 3.4 - give me a day or so to figure out how to test it.

**Comment by TD22057** [comment]
Please give it a try now - I was able to use miniconda to get a python 3.4, 3.5, and 3.6 install and was able to start it up on all three now with the changes that were submitted.

**Comment by house97** [comment]
I can run insteon-mqtt manually when I am sudoing as the insteon user, and all works well.  I verified the path "/opt/insteon-mqtt/bin/insteon-mqtt start /opt/insteon-mqtt/config.yaml" is correct.
When adding it as a service, and starting the service, I get the same error.

**Comment by TD22057** [comment]
Sorry - I'm not sure what would be different between sudo'ing to the insteon user and the startup service  but clearly something must be different.  Is there any chance the service is running from a different directory (or using a different version of the software), has a different PYTHONPATH, or is using a different version of python?

**Comment by house97** [comment]
I think that somehow the startup service was not running the service in the virtual environment.  I re-activated the venv and it got past that.
Now, I'm tripping over a different issue in starting the service.  
```python
● insteon-mqtt.service - Insteon MQTT Bridge
   Loaded: loaded (/etc/systemd/system/insteon-mqtt.service; disabled)
   Active: failed (Result: exit-code) since Fri 2017-12-22 21:15:36 EST; 10s ago
  Process: 1269 ExecStart=/opt/insteon-mqtt/bin/insteon-mqtt start /opt/insteon-mqtt/config.yaml (code=exited, status=1/FAILURE)
 Main PID: 1269 (code=exited, status=1/FAILURE)

Dec 22 21:15:36 homeassist-01 insteon-mqtt[1269]: config.apply(cfg, mqtt_handler, modem)
Dec 22 21:15:36 homeassist-01 insteon-mqtt[1269]: File "/opt/insteon-mqtt/lib/python3.4/site-packages/insteon_mqtt/config.py", line 42, in apply
Dec 22 21:15:36 homeassist-01 insteon-mqtt[1269]: modem.load_config(config['insteon'])
Dec 22 21:15:36 homeassist-01 insteon-mqtt[1269]: File "/opt/insteon-mqtt/lib/python3.4/site-packages/insteon_mqtt/Modem.py", line 103, in load_config
Dec 22 21:15:36 homeassist-01 insteon-mqtt[1269]: os.makedirs(save_path)
Dec 22 21:15:36 homeassist-01 insteon-mqtt[1269]: File "/usr/lib/python3.4/os.py", line 237, in makedirs
Dec 22 21:15:36 homeassist-01 insteon-mqtt[1269]: mkdir(name, mode)
Dec 22 21:15:36 homeassist-01 insteon-mqtt[1269]: PermissionError: [Errno 13] Permission denied: 'data'
Dec 22 21:15:36 homeassist-01 systemd[1]: insteon-mqtt.service: main process exited, code=exited, status=1/FAILURE
Dec 22 21:15:36 homeassist-01 systemd[1]: Unit insteon-mqtt.service entered failed state.
```

**Comment by TD22057** [comment]
It's a simple directory problem - the error is that it can't write to 'data' which is a directory name in your config.yaml file.  The simplest thing to do is tell the service to switch directories first.  Add this line to your .service file:

```
[Service]
WorkingDirectory=/opt/insteon-mqtt
```

Then you can use relative paths if you want.  As long as the insteon user has permissions in /opt/insteon-mqtt, it should be able create the data directory.

**Comment by house97** [comment]
Perfect!  Thanks for your patience with me.
